# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
 name: MyLinux
 demands:
 - agent.name -equals Agent1

variables:
  solution: '**/*.sln'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore Nugets' 
  inputs:
    azureSubscription: 'Azure subscription 1(9a6ae428-d8c3-44fe-bdf2-4e08593901a0)'
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build' 
  inputs:
    arguments: '--configuration Release'
    azureSubscription: 'Azure subscription 1(9a6ae428-d8c3-44fe-bdf2-4e08593901a0)'
    command: 'build'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests' 
  inputs:
    azureSubscription: 'Azure subscription 1(9a6ae428-d8c3-44fe-bdf2-4e08593901a0)'
    command: 'test'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Publish App' 
  inputs:
    arguments: '--configuration Release'
    azureSubscription: 'Azure subscription 1(9a6ae428-d8c3-44fe-bdf2-4e08593901a0)'
    command: 'publish'
    publishWebProjects: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/WebApplicationert/bin/Release/net7.0/publish.zip'
    publishLocation: 'pipeline'
